# Generated by Django 2.1.7 on 2019-03-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='终端识别号')),
            ],
            options={
                'verbose_name': '终端',
                'verbose_name_plural': '终端',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='任务编号')),
                ('file', models.FileField(upload_to='static/usr/uploads/files/%Y/%m/%d/', verbose_name='文件')),
                ('create_date', models.CharField(max_length=19, verbose_name='创建日期')),
                ('finished', models.BooleanField(default=False, verbose_name='已经打印')),
                ('finished_date', models.CharField(max_length=19, null=True, verbose_name='打印日期')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Data.Client', verbose_name='打印终端')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='RabbitMQNode',
            fields=[
                ('url', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='节点地址')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('nickname', models.CharField(max_length=32, verbose_name='用户昵称')),
                ('file_count', models.IntegerField(default=0, verbose_name='文件数量')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Data.User', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='client',
            name='rabbitmq_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Data.RabbitMQNode', verbose_name='依赖节点'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Data.User', verbose_name='所属用户'),
        ),
    ]
