# Generated by Django 2.1.7 on 2019-03-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.CharField(max_length=24, verbose_name='任务编号')),
                ('account', models.CharField(max_length=10, verbose_name='所属账号')),
                ('file_name', models.CharField(max_length=128, verbose_name='文件名')),
                ('file_path', models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='文件路径')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('finished', models.BooleanField(verbose_name='已经打印')),
                ('finished_date', models.DateField(blank=True, null=True, verbose_name='打印日期')),
                ('finished_locate', models.CharField(max_length=128, verbose_name='打印地点')),
            ],
            options={
                'verbose_name': '任务列表',
                'verbose_name_plural': '任务列表',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account', models.CharField(max_length=10, verbose_name='账号')),
                ('user_name', models.CharField(max_length=30, verbose_name='用户名')),
                ('file_count', models.IntegerField(verbose_name='文件数量')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
