# Generated by Django 2.1.7 on 2019-03-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='任务编号')),
                ('file', models.FileField(upload_to='usr/uploads/files/%Y/%m/%d/', verbose_name='文件')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('finished', models.BooleanField(default=False, verbose_name='已经打印')),
                ('finished_date', models.DateField(null=True, verbose_name='打印日期')),
                ('finished_locate', models.CharField(max_length=128, null=True, verbose_name='打印地点')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('nickname', models.CharField(max_length=30, verbose_name='用户昵称')),
                ('file_count', models.IntegerField(default=0, verbose_name='文件数量')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.User', verbose_name='所属用户'),
        ),
    ]
