# Generated by Django 2.1.7 on 2019-03-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_auto_20190302_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='文件'),
        ),
    ]
