# Generated by Django 2.1.7 on 2019-03-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20190302_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobId',
            field=models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='任务编号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='账号'),
        ),
    ]
