# Generated by Django 2.1.7 on 2019-03-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_auto_20190302_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['-create_date'], 'verbose_name': '任务', 'verbose_name_plural': '任务集合'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户集合'},
        ),
    ]
